import React, { cache } from 'react';
import './globals.css';
import type { Metadata } from 'next';
import { Josefin_Sans, Francois_One } from 'next/font/google';
import NavBar from '@/components/navigation/NavBar';
import ReduxProvider from '@/store/ReduxProvider';
import {
  getAllDesktopNavigationLinks,
  getAllNavigationLinks,
  getAllSocialMedia,
  getContactInfos,
} from '@/lib/queries';
import Footer from '@/components/global/Footer';

import { Analytics } from '@vercel/analytics/react';
import client from '../../../sanity/lib/client';

const josefin = Josefin_Sans({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-josefin',
});

const francoisOne = Francois_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-francois_one',
});

export const metadata: Metadata = {
  title: 'Rakonto',
  description: 'Generated by create next app',
  colorScheme: 'only light',
};

export const revalidate = 60;

const clientFetch = cache(client.fetch.bind(client));

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navLinks = await clientFetch(getAllNavigationLinks);
  const desktopNavLinks = await clientFetch(getAllDesktopNavigationLinks);
  const socialMedia = await clientFetch(getAllSocialMedia);
  const contactInfos = await clientFetch(getContactInfos);

  return (
    <html className="bg-background  " lang="en">
      <body
        className={`${josefin.variable} ${francoisOne.variable}  flex flex-col items-center justify-center  text-textColor `}
      >
        <ReduxProvider>
          <NavBar
            navLinks={navLinks}
            desktopNavLinks={desktopNavLinks}
            socialMedia={socialMedia}
          />
          {children}
          <Footer contactInfos={contactInfos[0]} socialMedia={socialMedia} />
        </ReduxProvider>
        <Analytics />
      </body>
    </html>
  );
}
